ai:
    platform:
        gemini:
            api_key: '%env(GEMINI_AI_KEY)%'
    agent:
        gemini:
            model:
                class: 'Symfony\AI\Platform\Bridge\Gemini\Gemini'
                name: !php/const Symfony\AI\Platform\Bridge\Gemini\Gemini::GEMINI_2_FLASH
            tools:
                 - 'Symfony\AI\Agent\Toolbox\Tool\SerpApi'
#                 - 'App\Ai\Tool\CustomTool'
